# Generated by Django 4.2.2 on 2023-07-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekeruser',
            name='tech_stack',
        ),
        migrations.DeleteModel(
            name='TechStack',
        ),
    ]
