# Generated by Django 4.2.2 on 2023-07-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_jobapplication_job_seekers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='job_seeker',
            new_name='certification_of_job_seeker',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='job_seeker',
            new_name='education_of_job_seeker',
        ),
        migrations.RenameField(
            model_name='endorsement',
            old_name='job_seeker',
            new_name='endorsement_of_job_seeker',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_seekers',
            new_name='placed_by_job_seeker',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_listing',
            new_name='placed_for_job_listing',
        ),
        migrations.RenameField(
            model_name='jobseekeruser',
            old_name='language',
            new_name='language_known',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='job_seeker',
            new_name='recommendation_of_job_seeker',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='job_seeker',
            new_name='skill_of_job_seeker',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='job_seeker',
            new_name='experience_of_job_seeker',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
    ]
