# Generated by Django 4.2.2 on 2023-07-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_job_seeker_certification_certification_of_job_seeker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='placed_for_job_listing',
            new_name='job_listing',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='placed_by_job_seeker',
            new_name='job_seekers',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_listing', 'application_date')},
        ),
    ]
